config/routes.rb
Rails.application.routes.draw do
 

 resources :users, :sessions, :posts

  resources :posts do
    resources :comments
  end 

  delete '/delete/posts/:id', to: 'posts#destroy', as: 'destroy_post' 
  
  delete 'delete/users/:id', to: 'users#destroy', as: 'destroy_user'

  get '/posts/:id', to: 'posts#show'

  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/session.rb
class Session < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :session
	has_many :posts
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 def index
    @posts = Post.all.order('created_at DESC')
  end 
  def new
    @post = Post.new

  end 
  def create
    @post = Post.new(post_params)
      if @post.save
      redirect_to @post
      else 
      render 'new'
      end 
  end 
  def show
    @post = Post.all
  end 

  def edit
    @post = Post.find(params[:id])
  end 
  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit(:title, :post))
      redirect_to @post
    else
      render 'edit'
    end 
  end 
  def destroy
    @post= Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end 

  private
  def post_params
    params.require(:post).permit(:title, :post)
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @session = Session.new
  end


  def create
    @user = User.where(email: params[:email]).first

    

   if @user && @user.username == params[:username] &&
         @user.password == params[:password] 


      flash[:notice] = "You have logged in successfully"
      redirect_to session_path(@user)
  

    elsif @user == nil

      flash[:alert] = "Fields cannot be left blank.  Please try again"
      redirect_to new_session_path  
  
    elsif @user.password == nil ||
          @user.username == nil
    
      flash[:alert] = "Fields cannot be left blank.  Please try again"
      redirect_to new_session_path 


    elsif    @user.email != params[:email] 
          
      flash[:notice] = "We have no record of that account. Please create an account."
      redirect_to new_session_path  

elsif 
          @user.username != nil || params[:username] &&
          @user.password != nil || params[:password] 


      flash[:notice] = "Your username or password did not match your email account. Please try again."
      redirect_to new_session_path

    else
      flash[:alert] = "There was a problem logging in."
      redirect_to new_session_path      

end
end



	def show
    @user = User.find(params[:id])
	end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have logged out successfully"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
 class UsersController < ApplicationController

  def index
    @user = User.all
  end

  def create
  @user = User.new(user_params)
    if @user.save
          flash[:notice] = "Your account was created
          successfully. Please log in."
          redirect_to new_session_path
      else
        flash[:alert] = "There was a problem saving your
        account."
        redirect_to new_user_path
    end
  end
  
    

   def new
      @user = User.new
   end


   def edit
    current_user
   end

   def update
    
      if @user.update_attributes(user_params)
          # Handle a successful update.
      else
        render 'edit'
      end
   end


     def show
      @user = User.all.order('created_at DESC')
     end

  

    def destroy
      current_user
      if @user.destroy
      flash[:notice] = "Your account was successfully deleted."
      redirect_to root_path
      else
        flash[:alert] = "There was a problem deleting your account."
        redirect_to destroy_user_path
      end
     end

   

     private


  def current_user
    @user = User.find(params[:id])
  end


  def user_params
    params.require(:user).permit(:username, :email, :password, :fname, :lname)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewFullBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	
				
			
			
			
	<%= flash[:notice] if flash[:notice] %>
	<%= flash[:alert] if flash[:alert] %>

			<%= yield %>


		
		
			
		





</body>
</html>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
	<div id="error">
		<h2><%= pluralize(@post.errors.count, "error")%> prevented this post from saving</h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
			<li><%= @msg %></li>
			<% end %>

		</ul>
	</div>
	<% end %>


	<h1>Edit Your Posts Below</h1>
<p>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
</p>

<p> 
	<%= f.label :post %><br>
	<%= f.text_area :post %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

app/views/posts/index.html.erb
<div class="title">
		Live Feed!
	</div>

<% @posts.each do |post| %>

	<div class="post_content">
		<br>
		<br>	<%= post.title %> <br>
		<br>	<%= post.post %> <br>
		<br>
	</div>


<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
	<div id="error">
		<h2><%= pluralize(@post.errors.count, "error")%> prevented this post from saving</h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
			<li><%= @msg %></li>
			<% end %>

		</ul>
	</div>
	<% end %>
<p>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
</p>

<p> 
	<%= f.label :post %><br>
	<%= f.text_area :post %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>
		Posts
	</title>
</head>
<body>
	<% if @user = User.find(params[:id]) %>

<% @post.each do |post| %>
<div id="post_content">
	<%= post.title %>
<p class="date">
	submitted <%= time_ago_in_words(post.created_at) %> Ago.
</p>
<p class="post">
	<%= post.post %>
	| <%= link_to 'Edit', edit_post_path(post.id) %>
	| <%= link_to 'Delete', destroy_post_path(post.id), method: :delete %>
</p>
<div class="comments">
	<h3>Add a comment</h3>
	
</div>
	<% end %>
	
	<% else %>

	<%= flash[:alert] = "There was a problem displaying your posts" %>

	<% end %>

</div>

</body>
</html>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Sign-up!</title>
	</head>

	<body>
	<div class="form">
	<header>	
		<h2>Sign up Below!</h2>
	</header>
</div>

	<div class="sign_up">
	
	<%= form_for User.new do |f| %>
	
	<p>
	  <%=f.label :username %>
	  <%=f.text_field :username %>
	</p>

	<p>
	  <%=f.label :password %>
	  <%=f.password_field :password %>
	</p>

	<p>
	  <%=f.label :fname %>
	  <%=f.text_field :fname %>
	</p>

	<p>
	  <%=f.label :lname %>
	  <%=f.text_field :lname %>
	</p>

	<p>
	  <%=f.label :email %>
	  <%=f.email_field :email %>
	</p>

	<p>
	  <%=f.label :birthday %>
	  <%=f.date_field :birthday %>
	</p>

	<p>
	  <%=f.submit :create %>
	</p>

	</div>

	<% end %>

	<%= link_to 'Home', root_path %> 

	</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Brain Food</title>
	</head>

	<body>


		<div class="toolbar">
		<header>
		<div class="title">
		<h2>Brain Food!</h2>		
		</div>

		<div class="nav">

		<nav>
			
			
				
				<%= link_to 'Create an Account', new_user_path %> |
				<%= link_to 'Sign-in', new_session_path %>

				 </nav>
			</div>
		</header>
	</div>

	<div class="main">
		<div class="about">
		<p>Welcome to Brain food! Here users can post articles that are informative, thought-provoking, or simply interesting--articles that feed your brain!  But don't just stop at sharing articles! Create an account at Brain Food.  Then, feel free to add your own thoughts and discuss with others!
		</p>
		</div>

		<div class="brain">
		<%= image_tag("http://cdn.vectorstock.com/i/composite/80,89/healthy-brain-food-cartoon-vector-1548089.jpg", :alt => "rss feed") %>
		</div>
	</div>
	
	</body>

</html>